<h1>Лабораторная работа №2</h1>

<h2>Работа с библиотеками NumPy, pandas</h2>

In [3]:
import numpy as np
import pandas as pd

In [30]:
list_1 = [0, 1, 2, 3, 4]
arr_1d = np.array(list_1)
print(arr_1d)
print(arr_1d.dtype)
type(arr_1d)

[0 1 2 3 4]
int32


numpy.ndarray

In [29]:
b = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
b.shape

(2, 4)

In [28]:
b = np.array([(1.3, 2.4),(0.3, 4.1)])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [27]:
for i in range(len(list_1)):
    list_1[i] += 1
    
arr_1d += 1

print(list_1)
print(arr_1d)

for i in range(len(list_1)):
    list_1[i] -= 1
    
arr_1d -= 1

print(list_1)
print(arr_1d)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [26]:
zeros = np.zeros(10)
ones = np.ones(10)
arrange_1 = np.arange(10)
linspace_1 = np.linspace(0,1,5)

print('zeroes', zeros)
print('ones', ones)
print('arange_1', arrange_1)
print('linspace_1', linspace_1)

zeroes [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arange_1 [0 1 2 3 4 5 6 7 8 9]
linspace_1 [0.   0.25 0.5  0.75 1.  ]


In [25]:
print(np.arange(10)[5:9])

arange = np.arange(10).reshape(2, 5)

print('arrange_1=', arange)
print('arrange_2=', arange[:, 3:])
print('arrange_3=', arange[arange%2 == 1])

[5 6 7 8]
arrange_1= [[0 1 2 3 4]
 [5 6 7 8 9]]
arrange_2= [[3 4]
 [8 9]]
arrange_3= [1 3 5 7 9]


In [24]:
a = np.arange(6)
print(a.shape)

a2 = a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

In [12]:
df = pd.DataFrame({'int_col' : [1, 2, 6, 8, -1], 'float_col' : [0.1, 0.2, 0.2, 10.1, None], 'str_col' : ['a', 'b', None, 'c', 'a']})
df

int_col  float_col str_col
0        1        0.1       a
1        2        0.2       b
2        6        0.2    None
3        8       10.1       c
4       -1        NaN       a

In [21]:
cities = {"name": ["London", "Berlin", "Madrid", "Rome",
"Paris", "Vienna", "Bucharest", "Hamburg",
"Budapest", "Warsaw", "Barcelona",
"Munich", "Milan"],
"population": [8615246, 3562166, 3165235, 2874038,
2273305, 1805681, 1803425, 1760433,
1754000, 1740119, 1602386, 1493900,
1350680],
"area": [1572, 891.85, 605.77, 1285,
105.4, 414.6, 228, 755,
525.2, 517, 101.9, 310.4,
181.8]
}

city_frame = pd.DataFrame(cities,
columns=["population", "area"],
index=cities["name"])
print(city_frame)

           population     area
London        8615246  1572.00
Berlin        3562166   891.85
Madrid        3165235   605.77
Rome          2874038  1285.00
Paris         2273305   105.40
Vienna        1805681   414.60
Bucharest     1803425   228.00
Hamburg       1760433   755.00
Budapest      1754000   525.20
Warsaw        1740119   517.00
Barcelona     1602386   101.90
Munich        1493900   310.40
Milan         1350680   181.80


In [15]:
df.loc[:,['float_col','int_col']]

float_col  int_col
0        0.1        1
1        0.2        2
2        0.2        6
3       10.1        8
4        NaN       -1

In [16]:
df.columns

Index(['int_col', 'float_col', 'str_col'], dtype='object')

In [17]:
df.describe()

int_col  float_col
count  5.000000    4.00000
mean   3.200000    2.65000
std    3.701351    4.96689
min   -1.000000    0.10000
25%    1.000000    0.17500
50%    2.000000    0.20000
75%    6.000000    2.67500
max    8.000000   10.10000

In [18]:
df.describe(include=['object', 'bool'])

str_col
count        4
unique       3
top          a
freq         2

In [23]:
city_frame.population.value_counts()

population
8615246    1
3562166    1
3165235    1
2874038    1
2273305    1
1805681    1
1803425    1
1760433    1
1754000    1
1740119    1
1602386    1
1493900    1
1350680    1
Name: count, dtype: int64

## Задачи с NumPy


In [450]:
# 1.1
my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [451]:
# 2.1
my_array_10 = my_array[my_array % 10 == 0]
my_array_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [452]:
# 3.1
two_columns_array = my_array_10.reshape(-1, 2)
two_columns_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [453]:
# 4.1
my_second_array = two_columns_array[:] - 5
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [454]:
#5.1
combined = np.hstack((two_columns_array, my_second_array))
combined

array([[ 10,  20,   5,  15],
       [ 30,  40,  25,  35],
       [ 50,  60,  45,  55],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [455]:
two_columns_array = two_columns_array.T
two_columns_array

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100]])

In [456]:
combined = combined.T
combined

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100],
       [  5,  25,  45,  65,  85],
       [ 15,  35,  55,  75,  95]])

In [457]:
#6.1
combined[1] = combined[1] / two_columns_array[0]
combined[2] = combined[2] / two_columns_array[1]
combined


array([[10, 30, 50, 70, 90],
       [ 2,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0],
       [15, 35, 55, 75, 95]])

In [458]:
#7.1
new_combined = np.delete(combined, np.where(np.any(combined < 3, axis=1)), axis=0)
new_combined

array([[10, 30, 50, 70, 90],
       [15, 35, 55, 75, 95]])

In [496]:
#8.1
new_array = np.hstack((two_columns_array.T, my_second_array))
new_array = np.resize(new_array, (3, 4))
print("До изменения:\n",new_array)
new_array[0], new_array[2] = new_array[2].copy(), new_array[0].copy()
print("После изменения:\n",new_array)

До изменения:
 [[10 20  5 15]
 [30 40 25 35]
 [50 60 45 55]]
После изменения:
 [[50 60 45 55]
 [30 40 25 35]
 [10 20  5 15]]


In [503]:
medians = np.median(new_array, axis=1)
means = np.mean(new_array, axis=1)
stds = np.std(new_array, axis=1)
print("Медианы:",medians)
print("Среднее:",means)
print("Отклонения:",stds)

Медианы: [52.5 32.5 12.5]
Среднее: [52.5 32.5 12.5]
Отклонения: [5.59016994 5.59016994 5.59016994]


In [505]:
max_values = np.max(new_array, axis=1, keepdims=True)
normalized_array = new_array / max_values
normalized_array

array([[0.83333333, 1.        , 0.75      , 0.91666667],
       [0.75      , 1.        , 0.625     , 0.875     ],
       [0.5       , 1.        , 0.25      , 0.75      ]])

## Задачи с Pandas


In [321]:
global_population = pd.read_csv('Global Population Trends(2016-2022).csv')
global_population

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

In [322]:
global_population.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [323]:
global_population.shape

(1073, 12)

In [324]:
global_population.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [325]:
global_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [326]:
for column in global_population.columns:
    global_population = global_population[global_population[column]!='-']

In [327]:
global_population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 1071
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                561 non-null    object 
 1   Year                   561 non-null    int64  
 2   Total Population       561 non-null    object 
 3   Urban Population       561 non-null    object 
 4   Rural Population       561 non-null    object 
 5   Population Density     561 non-null    object 
 6   Life Expectancy        561 non-null    object 
 7   Birth Rate             561 non-null    float64
 8   Death Rate             561 non-null    float64
 9   Fertility Rate         561 non-null    object 
 10  Infant Mortality Rate  561 non-null    object 
 11  Growth Rate            561 non-null    object 
dtypes: float64(2), int64(1), object(9)
memory usage: 57.0+ KB


In [328]:
global_population['Total Population'] = global_population['Total Population'].map(lambda x: x.replace(',', '')).astype(int)
global_population['Urban Population'] = global_population['Urban Population'].map(lambda x: x.replace(',', '')).astype(int)
global_population['Rural Population'] = global_population['Rural Population'].map(lambda x: x.replace(',', '')).astype(int)
global_population['Population Density'] = global_population['Population Density'].map(lambda x: x.replace(',', '')).astype(int)
global_population['Life Expectancy'] = global_population['Life Expectancy'].map(lambda x: x).astype(float)
global_population['Fertility Rate'] = global_population['Fertility Rate'].map(lambda x: x).astype(float)
global_population['Infant Mortality Rate'] = global_population['Infant Mortality Rate'].map(lambda x: x).astype(float)
global_population['Growth Rate'] = global_population['Growth Rate'].map(lambda x: x).astype(float)


In [330]:
global_population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 1071
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                561 non-null    object 
 1   Year                   561 non-null    int64  
 2   Total Population       561 non-null    int32  
 3   Urban Population       561 non-null    int32  
 4   Rural Population       561 non-null    int32  
 5   Population Density     561 non-null    int32  
 6   Life Expectancy        561 non-null    float64
 7   Birth Rate             561 non-null    float64
 8   Death Rate             561 non-null    float64
 9   Fertility Rate         561 non-null    float64
 10  Infant Mortality Rate  561 non-null    float64
 11  Growth Rate            561 non-null    float64
dtypes: float64(6), int32(4), int64(1), object(1)
memory usage: 48.2+ KB


In [331]:
max_year = global_population.Year.max()

max_birth_rate = global_population['Birth Rate'].max()
min_birth_rate = global_population['Birth Rate'].min()

max_death_rate = global_population['Death Rate'].max()
min_death_rate = global_population['Death Rate'].min()

dataframe_statistics = global_population.describe()

print('Максимальный год:',max_year)
print('Максимальный процент рождаемости:',max_birth_rate)
print('Минимальный процент рождаемости:',min_birth_rate)
print('Максимальный процент смертности:',max_death_rate)
print('Минимальный процент смертности:',min_birth_rate)
print('Описание статистике по таблице:\n',dataframe_statistics)

Максимальный год: 2020
Максимальный процент рождаемости: 46.127
Минимальный процент рождаемости: 5.3
Максимальный процент смертности: 18.0
Минимальный процент смертности: 5.3
Описание статистике по таблице:
               Year  Total Population  Urban Population  Rural Population  \
count   561.000000      5.610000e+02      5.610000e+02      5.610000e+02   
mean   2019.000000      4.099916e+07      2.273374e+07      1.826542e+07   
std       0.817225      1.487007e+08      7.642012e+07      7.916924e+07   
min    2018.000000      1.086500e+04      6.778000e+03      2.831000e+03   
25%    2018.000000      2.225702e+06      1.248816e+06      6.930040e+05   
50%    2019.000000      9.329227e+06      4.537328e+06      2.735697e+06   
75%    2020.000000      3.087064e+07      1.576521e+07      1.108990e+07   
max    2020.000000      1.411100e+09      8.668105e+08      9.086850e+08   

       Population Density  Life Expectancy  Birth Rate  Death Rate  \
count          561.000000       561.0

In [332]:
global_population.sort_values(by=['Life Expectancy', 'Total Population'], ascending=True)

Country  Year  Total Population  Urban Population  Rural Population  \
188         Chad  2018          15604210           3598175          12006035   
189         Chad  2019          16126866           3754173          12372693   
190         Chad  2020          16644701           3914834          12729867   
696      Nigeria  2018         198387623          99876265          98511358   
697      Nigeria  2019         203304492         104004479          99300013   
..           ...   ...               ...               ...               ...   
930  Switzerland  2019           8575280           6332759           2242521   
885        Spain  2019          47134837          37974181           9160656   
478        Japan  2019         126633000         116119928          10513072   
477        Japan  2018         126811000         116179166          10631834   
479        Japan  2020         126261000         115884871          10376129   

     Population Density  Life Expectancy  Birth Rate  Death Rate  \
188                  12             53.0      44.370      12.671   
189                  13             53.0      44.229      12.369   
190                  13             53.0      43.849      12.486   
696                 218             53.0      38.248      13.239   
697                 223             53.0      37.849      12.989   
..                  ...              ...         ...         ...   
930                 217             84.0      10.000       7.900   
885                  94             84.0       7.600       8.800   
478                 347             84.0       7.000      11.200   
477                 348             84.0       7.400      11.000   
479                 346             85.0       6.800      11.100   

     Fertility Rate  Infant Mortality Rate  Growth Rate  
188           6.464                   71.0          3.0  
189           6.412                   69.3          3.0  
190           6.346                   67.6          3.0  
696           5.447                   75.5          2.0  
697           5.379                   73.9          2.0  
..              ...                    ...          ...  
930           1.480                    3.5          1.0  
885           1.230                    2.7          1.0  
478           1.360                    1.8          0.0  
477           1.420                    1.9          0.0  
479           1.330                    1.8          0.0  

[561 rows x 12 columns]

In [338]:
global_population.loc[global_population['Total Population'] == global_population['Total Population'].max()]

Country  Year  Total Population  Urban Population  Rural Population  \
204   China  2020        1411100000         866810508         544289492   

     Population Density  Life Expectancy  Birth Rate  Death Rate  \
204                 150             78.0        8.52        7.07   

     Fertility Rate  Infant Mortality Rate  Growth Rate  
204           1.281                    5.5          0.0

In [339]:
global_population.loc[global_population['Total Population'] == global_population['Total Population'].min()]

Country  Year  Total Population  Urban Population  Rural Population  \
994  Tuvalu  2018             10865              6778              4087   

     Population Density  Life Expectancy  Birth Rate  Death Rate  \
994                 362             64.0      23.508      10.107   

     Fertility Rate  Infant Mortality Rate  Growth Rate  
994           3.209                   20.0          0.0

In [337]:
global_population.to_excel('formatted_data.xlsx', index=False)